## **Session 2** - Data Representation in Scikit-learn
Scikit-learn primarily uses two main types of data structures:

- **Feature Matrix (X):** Represents the input features
- **Target Vector (y):** Represents the output or target variable (for supervised learning)

---

#### Load dataset

سایکییت لرن تعدادی دیتا ست آماده دارد که برای اهداف تمرینی و آموزشی می توان از آنها استفاده کرد

In Scikit-learn, data is typically organized following the sample-feature convention:

- Each row represents a sample (an instance or observation)
- Each column represents a feature (an attribute or variable)

In [2]:
import numpy as np
from sklearn.datasets import load_iris #there is many other datasets too!

# load data set
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
iris.filename

'iris.csv'

❗️ Important Note: Scikit-learn expects 2D arrays for X, even when dealing with a single feature. You may need to reshape 1D arrays to 2D.

In [ ]:
# Reshaping a 1D array to 2D
X_1d = np.array([1, 2, 3, 4, 5])
X_2d = X_1d.reshape(-1, 1) # Best syntax for reshaping 1D array to 2D array, because it's not depends on number of elements
print(f"Original shape: {X_1d.shape}, Reshaped: {X_2d.shape}")

### Data representation
![](images/img_4.png)

 #### Feature Matrix (X)
- 2D array (or matrix)
- Shape: (n_samples, n_features)
- Each row represents a single sample
- Each column represents a specific feature

---

#### Target Vector (y)
- 1D array
- Shape: (n_samples,)
- Each element corresponds to a sample in the feature matrix

---

#### Handling Mismatch Between X and y
درواقع تعداد سطر ها در این دو ماتریس باید یکسان باشد.

برای هندل کردن این مشکل بهتر است همیشه هنگام لود $X$ و $Y$ وجود یا عدم وجود این مشکل را بررسی کنیم


In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = np.random.rand(100, 5) # 100 Sample , 5 features
Y = np.random.randint(0, 2, 90) # Only 90 targets

try:
    X_train, X_test, y_train, y_test = train_test_split(X, Y)
    model = LogisticRegression().fit(X_train, y_train)
except ValueError as e:
    print(f"ValueError: {e}")

ValueError: Found input variables with inconsistent numbers of samples: [100, 90]


### Handling Different Data Types

#### Numerical Data

ساده ترین و سرراست ترین نوع داده برای کار در سایکیت لرن

Scikit-learn works best with float64 data type for numerical features.



In [15]:
import numpy as np
from sklearn.preprocessing import StandardScaler

X_continuous = np.array([[1.0, 2.5, 3.2], [4.1, 5.7, 6.3], [7.8, 8.9, 9.0]])

# Standardizing the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_continuous)

#  Standardizing means to scale data to mean = 0 and standard-deviation = 1

In [17]:
print(f"Original data: \n {X_continuous}, \n Scaled data: \n {X_scaled}")

Original data: 
 [[1.  2.5 3.2]
 [4.1 5.7 6.3]
 [7.8 8.9 9. ]], 
 Scaled data: 
 [[-1.1871835  -1.22474487 -1.25190792]
 [-0.07195052  0.          0.05626552]
 [ 1.25913401  1.22474487  1.1956424 ]]


Discrete numerical data (integers) can also be used directly, but sometimes scaling or encoding might be beneficial.

داده‌های عددی گسسته (اعداد صحیح) نیز می‌توانند مستقیماً مورد استفاده قرار گیرند، اما گاهی اوقات مقیاس‌بندی یا کدگذاری ممکن است مفید باشد.


In [18]:
from sklearn.preprocessing import OneHotEncoder

X_discrete = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#One-Hot encoding for discrete data
encoder = OneHotEncoder(sparse_output=False)
x_encoded = encoder.fit_transform(X_discrete)

In [19]:
print(f"Original data: \n {X_discrete}, \n Scaled data: \n {x_encoded}")

Original data: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]], 
 Scaled data: 
 [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


#### Categorical data
For ordinal data (categories with a meaningful order), you can use OrdinalEncoder.

In [20]:
from sklearn.preprocessing import OrdinalEncoder

# Ordinal categorical data
X_ordinal = np.array(
    [["cold", "warm", "hot"], ["warm", "hot", "cold"], ["hot", "cold", "warm"]]
)

ordinal_encoder = OrdinalEncoder()
X_ordinal_encoded = ordinal_encoder.fit_transform(X_ordinal)

In [21]:
print(f"Originial data: \n {X_ordinal}, \n Encoded ordinal data: \n {X_ordinal_encoded}" )

Originial data: 
 [['cold' 'warm' 'hot']
 ['warm' 'hot' 'cold']
 ['hot' 'cold' 'warm']], 
 Encoded ordinal data: 
 [[0. 2. 1.]
 [2. 1. 0.]
 [1. 0. 2.]]


For nominal data (categories without inherent order), use OneHotEncoder.

In [22]:
# Nominal categorical data
X_nominal = np.array(
    [["red", "blue", "green"], ["blue", "green", "red"], ["green", "red", "blue"]]
)

onehot_encoder = OneHotEncoder(sparse_output=False)
X_nominal_encoded = onehot_encoder.fit_transform(X_nominal)

In [24]:
print(f"Original data: {X_nominal}, \n encoded data: \n {X_nominal_encoded}")

Original data: [['red' 'blue' 'green']
 ['blue' 'green' 'red']
 ['green' 'red' 'blue']], 
 encoded data: 
 [[0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0.]]


#### Text Data

Text data requires transformation into numerical features before it can be used in Scikit-learn models.

The most common approach is to use CountVectorizer or TfidfVectorizer.



In [25]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Sample text data
text_data = [
    "The quick brown fox",
    "jumps over the lazy dog",
    "The lazy dog sleeps"
]

# Using CountVectorizer
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(text_data)

# Using TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(text_data)

In [27]:
print(f"Count Vectorizer:\n {X_count.toarray()} , \n TF-IDF Vectorizer:\n {X_tfidf.toarray()}")

Count Vectorizer:
 [[1 0 1 0 0 0 1 0 1]
 [0 1 0 1 1 1 0 0 1]
 [0 1 0 0 1 0 0 1 1]] , 
 TF-IDF Vectorizer:
 [[0.54645401 0.         0.54645401 0.         0.         0.
  0.54645401 0.         0.32274454]
 [0.         0.40619178 0.         0.53409337 0.40619178 0.53409337
  0.         0.         0.31544415]
 [0.         0.4804584  0.         0.         0.4804584  0.
  0.         0.63174505 0.37311881]]


#### Handling Mixed Data Types


In [28]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [29]:
# Sample mixed-type data
data = pd.DataFrame({
    'age': [30, 40, 50, 60],
    'income': [50000, 60000, np.nan, 80000],
    'gender': ['M', 'F', 'M', 'F'],
    'category': ['A', 'B', 'A', 'C']
})

In [31]:
iris = load_iris()
X, y = iris.data, iris.target

pipline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression())
])

In [33]:
pipline.fit(X, y)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('imputer', ...), ('scaler', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'mean'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If 

### Features of Scikit-Learn Data Preprocessors
![](images/img_5.png)